# 基本配置
name: "Legolas' Blogs"
author: legolas
url: https://legolasng.github.io
resume_site: https://github.com/legolasNg
baseurl: ""
description: keep it simple, stupid !
meta_description: "<font color='red'> Errors = (More Code)<sup>2</sup> </font>"
motto: Talk is cheap, Show me the code !
banner: legolas

# social
github:     https://github.com/legolasNg
weibo:      http://weibo.com/219920327
facebook:   https://www.facebook.com/wulegolas
twitter:    https://twitter.com/legolas_ng
linkedin:   https://www.linkedin.com/in/legolasNg
email:      wujianye3@gmail.com

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"

github_username: legolasNg

# markdown解析器
markdown: kramdown
kramdown:
    input: GFM
#highlighter: rouge

# 评论区设置
FB:
  comments :
    provider : disqus
    disqus :
        short_name : legolasng